trigger:
- main

# pool: TIS-Linux-Pool
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy
    jobs:
    - deployment: DeployJob
      timeoutInMinutes: 10
      environment:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: CmdLine@2
                displayName: 'Install Dependencies'
                inputs:
                  script: |
                    echo "Hello World!"