trigger:
 - main

pool: TIS_POOL_RANCHER_NP

steps:

- script: |
    python -V
  displayName: 'Python Version'
  condition: always()

- script: |
    python3.11 -V
  displayName: 'Python 3.11 Version'
  condition: always()

- script: |
    sleep 1m
  displayName: 'Delay'
